---
#==========================================
#
#Created by HaykalPRO
# Version: 1
#   Created at: 4/Agustus/2021
#
#==========================================
#
#Basic setup:
# Use "\n" to add a new line
# Use "ยง" to add a color!
# Use "" or "ยงr " to leave it blank (empty)
# Your World Name
#
#==========================================
title: "JoinUI"
content: "Your Content"
button: "button-name"
join-message: "{name} has join Server!"
#==========================================
