---
#==========================================
#
#Created by HaykalPRO
# Version: 1
#   Created at: 28/May/2021
#
#==========================================
#
#Basic setup:
# Use "\n" to add a new line
# Use "§" to add a color!
# Use "" or "§r " to leave it blank (empty)
# Your World Name
#
#==========================================
#
# MESSAGE BUTTON ONE
MSG-ONE: "§aHi §6{player} §aWelcome To Server :)"
#
#==========================================
#
# MESSAGE BUTTON TWO
MSG-ONE: "§aEnjoy :)"
#
#==========================================
#
# MESSAGE BUTTON TWO
MSG-ONE: "§aEnjoy :)"
#
#==========================================
#
# TITLE JOIN UI
TITLE-JOINUI: "§l§bWELCOME"
#
#==========================================
#
# CONTENT JOIN UI
CONTENT-JOINUI: "Edit In Config"
#
#==========================================
#
# BUTTON 1
BUTTON-ONE: "Edit In Config"
#
#==========================================
#
# BUTTON 2
BUTTON-TWO: "Edit In Config"
#
#==========================================